const data = {
    products: [
        {
            _id: 1,
            name: "Nike Slim Shirt",
            image: "images/p1.jpg",
            price: 120,
            category: "Shirts",
            rating: 4.5,
            numReviews: 10,
            description: "High Quality Product.",
            brand: "Nike",
            countInStock: 5,
        },
        {
            _id: 2,
            name: "Addidas Fit Shirt",
            image: "images/p2.jpg",
            price: 90,
            category: "Shirts",
            rating: 4.5,
            numReviews: 15,
            description: "High Quality Product.",
            brand: "Addidas",
            countInStock: 6,
        },
        {
            _id: 3,
            name: "Lacoste Fit Shirt",
            image: "images/p3.jpg",
            price: 110,
            category: "Shirts",
            rating: 2.5,
            numReviews: 5,
            description: "High Quality Product.",
            brand: "Lee-Cooper",
            countInStock: 6,
        },
        {
            _id: 4,
            name: "Nike Trousers",
            image: "images/p4.jpg",
            price: 100,
            category: "Pants",
            rating: 5,
            numReviews: 8,
            description: "High Quality Product.",
            brand: "Nike",
            countInStock: 0,
            
        },
        {
            _id: 5,
            name: "Zara Trousers",
            image: "images/p5.jpg",
            price: 130,
            category: "Pants",
            rating: 3.5,
            numReviews: 6,
            description: "High Quality Product.",
            brand: "Zara",
            countInStock: 4,
        },
    ]
}
export default data;